../rtl/id.sv
../rtl/inst_rom.sv
../rtl/sopc_tb.sv
../rtl/if_id.sv
../rtl/ex_mem.sv
../rtl/defines.sv
../rtl/ex.sv
../rtl/mem.sv
../rtl/mem_wb.sv
../rtl/sopc.sv
../rtl/id_ex.sv
../rtl/pc_reg.sv
../rtl/regfile.sv
../rtl/openmis.sv
../rtl/hilo_reg.sv